checking for required memory on disk

diff --git a/ngsComposer b/ngsComposer
--- a/ngsComposer
+++ b/ngsComposer
@@ -176,32 +176,7 @@ cd $projdir
 samples_alt_dir="$(grep samples_alt_dir config.sh)"
 samples_alt_dir=${samples_alt_dir//*=}
 
-# Initial questions before running walkaway
-cd $projdir/samples
 
-free=$(df . | awk 'NR==2{print $4}')
-required=$(du -s . | awk '{print $1}') && required0=required
-if [[ "$(ls | head -n1)" =~ "gz" ]]; then required0=$((required*5)); fi
-if [[ -z $samples_alt_dir || $samples_alt_dir =~ False ]]; then
-  required1=$((required0 * required))
-  required=$((required + required1))
-else
-  required=$((required0 * required))
-fi
-if [[ "$free" -lt "$required" ]]; then
-	echo -e "${magenta}- You might not have enough disk space. ${white}\n"
-  echo -e "${magenta}- Free: $((free/1000000))G; Required(approx. 2x the size of fastq files): $((required/1000000))G  ${white}\n"
-	echo -e "${magenta}- Do you want to continue running ngsComposer? ${white}"
-	read -p "- y(YES) or n(NO)? " -n 1 -r
-	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-		printf '\n'
-		echo -e "${magenta}- Exiting ngsComposer ${white}\n"
-		sleep 5 && exit 1
-	fi
-fi
-
-
-cd $projdir
 if [[ ! -d samples ]]; then
   if [[ -z $samples_alt_dir || $samples_alt_dir =~ False ]]; then
     echo -e "${magenta}- samples folder is missing ${white}\n"
@@ -238,6 +213,31 @@ else
 	fi
 fi
 
+
+
+# Initial questions before running walkaway
+cd $projdir/samples
+
+free=$(df . | awk 'NR==2{print $4}')
+required=$(du -s . | awk '{print $1}') && required0=required
+if [[ "$(ls | head -n1)" =~ "gz" ]]; then required0=$((required*5)); fi
+if [[ -z $samples_alt_dir || $samples_alt_dir =~ False ]]; then
+  required1=$((required0 * required))
+  required=$((required + required1))
+else
+  required=$((required0 * required))
+fi
+if [[ "$free" -lt "$required" ]]; then
+	echo -e "${magenta}- You might not have enough disk space. ${white}\n"
+  echo -e "${magenta}- Free: $((free/1000000))G; Required(approx. 2x the size of fastq files): $((required/1000000))G  ${white}\n"
+	echo -e "${magenta}- Do you want to continue running ngsComposer? ${white}"
+	read -p "- y(YES) or n(NO)? " -n 1 -r
+	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+		printf '\n'
+		echo -e "${magenta}- Exiting ngsComposer ${white}\n"
+		sleep 5 && exit 1
+	fi
+fi
 
 cd $projdir
 test_bc=$(grep '^lib' config.sh | grep '_bc' | awk '{gsub(/=/,"\t"); print $2}')
